-- create
CREATE TABLE EMPLOYEE (
  Emp_Id INTEGER PRIMARY KEY,
  E_Name TEXT NOT NULL,
  E_Address TEXT NOT NULL
);

CREATE TABLE Phone_Number (
  Emp_Id INTEGER,
  Emp_Phone INTEGER NOT NULL,
  FOREIGN KEY (Emp_Id) REFERENCES EMPLOYEE (Emp_Id)
);

CREATE TABLE Department (
  Dept_No INTEGER PRIMARY KEY,
  Dept_Name TEXT NOT NULL,
  Job_Id INTEGER NOT NULL,
  Salary INTEGER NOT NULL
);
-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Deepak', 'Varanasi');
INSERT INTO EMPLOYEE VALUES (0002, 'Anupam', 'Bhopal');
INSERT INTO EMPLOYEE VALUES (0003, 'asg', 'Timbaktu');

INSERT INTO Phone_Number VALUES (0001, 9235007082);
INSERT INTO Phone_Number VALUES (0001, 8543055625);
INSERT INTO Phone_Number VALUES (0002, 993431994);
INSERT INTO Phone_Number VALUES (0003, 730916094);

INSERT INTO Department VALUES (01, 'CSE','101', '20000');
INSERT INTO Department VALUES (02, 'AIML','102', '15000');
INSERT INTO Department VALUES (03, 'Electrical','103', '10000');
-- fetch 
SELECT * FROM EMPLOYEE;
SELECT * FROM Phone_Number;
SELECT * FROM Department;
